server:
  port: 9000
  
  
spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: "環境変数もしくはオプションを使用すること"
    password:  "環境変数もしくはオプションを使用すること"
    default-encoding: "UTF-8"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    
